### ISSUE TITLE
Some UI doesnt have the "Ground glass" effect in Gandi Beatification plugin

### ISSUE THREAD

**Issue by fath11** [Gandi-IDE/gandi-plugins#14]
![image](https://github.com/Gandi-IDE/gandi-plugins/assets/124476952/d97b4f2c-f0a7-4a72-93d3-a2849b482899)
@kukemc

**Comment by kukemc** [comment]
> I know this，The reason this section lacks Ground glass is that when it's applied in full-screen mode, errors occur. Currently, I'm unaware of how to resolve this issue.😭我知道这一点，这部分缺少毛玻璃的原因是当它在全屏模式下应用时，会出现错误。目前，我不知道如何解决此问题。 😭

It's like this 
![image](https://github.com/Gandi-IDE/gandi-plugins/assets/95417077/ff79c1cb-55e6-43b7-a3ba-d71fe65ff4b2)

**Comment by kukemc** [comment]
![image](https://github.com/Gandi-IDE/gandi-plugins/assets/95417077/6daf2f70-e7f7-4fe2-9b00-608266029682)
relevant code

**Comment by kukemc** [comment]
Fixed

**Comment by little-starts** [comment]
this bug has fixed last week.

**Comment by little-starts** [comment]
> this bug has fixed last week.

by me
