### ISSUE TITLE
[插件问题]AI助手插件在100%默认比例下显示不全

### ISSUE THREAD

**Issue by MoreBugOfDog** [Gandi-IDE/gandi-plugins#43]
“AI助手“插件，在浏览器默认比例“100%”下，无法显示出对话框
![image](https://github.com/Gandi-IDE/gandi-plugins/assets/121487216/a28389ae-7b0c-40cf-b3ef-a4ee8657fd14)
这对于新手来说是致命的。

The “AI Assistant” plugin does not display the dialog box at the default browser scale of “100%”.
This is fatal for newbies.

**Comment by kukemc** [comment]
你屏幕分辨率太低了（）
![image](https://github.com/Gandi-IDE/gandi-plugins/assets/95417077/2785c6eb-3960-4f60-8e3e-4ceef3b7c255)

**Comment by zxq142857** [comment]
> “AI助手“插件，在浏览器默认比例“100%”下，无法显示出对话框 ![image](https://private-user-images.githubusercontent.com/121487216/334786562-a28389ae-7b0c-40cf-b3ef-a4ee8657fd14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxMjIzMDUsIm5iZiI6MTcxNzEyMjAwNSwicGF0aCI6Ii8xMjE0ODcyMTYvMzM0Nzg2NTYyLWEyODM4OWFlLTdiMGMtNDBjZi1iM2VmLWE0ZWU4NjU3ZmQxNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMVQwMjIwMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNThlMTAzNjRhZmZhYzdiMWQ5NWMwMGZhNDNhMDVmN2ZmODczZmQ1ODQwY2QzNjMyZWFkYmE4ODkyMzg3ZjkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SBY6LiRIa_do-JvHtIGlalSNvjW-wFD7oCFwXv1F9yw) 这对于新手来说是致命的。
> 
> The “AI Assistant” plugin does not display the dialog box at the default browser scale of “100%”. This is fatal for newbies.

这个弹窗的默认高度是600px, 一般的设备都是可以正常显示的，不知道你的是什么设备呢

**Comment by zxq142857** [comment]
找个了windows的笔记本，确实有这样的问题，这种笔记本可视高度才591px

**Comment by MoreBugOfDog** [comment]
> > “AI助手”插件，在浏览器默认比例“100%”下，无法显示出对话框 ![图像](https://private-user-images.githubusercontent.com/121487216/334786562-a28389ae-7b0c-40cf-b3ef-a4ee8657fd14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxMjIzMDUsIm5iZiI6MTcxNzEyMjAwNSwicGF0aCI6Ii8xMjE0ODcyMTYvMzM0Nzg2NTYyLWEyODM4OWFlLTdiMGMtNDBjZi1iM2VmLWE0ZWU4NjU3ZmQxNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMVQwMjIwMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNThlMTAzNjRhZmZhYzdiMWQ5NWMwMGZhNDNhMDVmN2ZmODczZmQ1ODQwY2QzNjMyZWFkYmE4ODkyMzg3ZjkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SBY6LiRIa_do-JvHtIGlalSNvjW-wFD7oCFwXv1F9yw) 这对于新手来说是致命的。
> > “AI Assistant”插件不会以默认浏览器比例“100%”显示对话框。这对新手来说是致命的。
> 
> 这个弹窗的默认高度是600px, 一般的设备都是可以正常显示的，不知道你的是什么设备呢

联想 Thinkpad

**Comment by jaggerzhong** [comment]
> “AI助手“插件，在浏览器默认比例“100%”下，无法显示出对话框 ![image](https://private-user-images.githubusercontent.com/121487216/334786562-a28389ae-7b0c-40cf-b3ef-a4ee8657fd14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5MjE4MDQsIm5iZiI6MTcxNzkyMTUwNCwicGF0aCI6Ii8xMjE0ODcyMTYvMzM0Nzg2NTYyLWEyODM4OWFlLTdiMGMtNDBjZi1iM2VmLWE0ZWU4NjU3ZmQxNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOVQwODI1MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYzEwMjlhNzQyM2FmNGE4YjJhYTdkZDYzYWZkZmRmYzhmYzRjZDU1YWIxZjc4NGUwM2JjYjAzOTI4N2E3YzMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hbCu-qu3yKiYat1IgouwbR7u6HIjz8K13DyIY2pSO_w) 这对于新手来说是致命的。
> 
> The “AI Assistant” plugin does not display the dialog box at the default browser scale of “100%”. This is fatal for newbies.

感谢反馈，固定尺寸确实会有这个问题，我处理一下。

**Comment by jaggerzhong** [comment]
#53
