### ISSUE TITLE
README.md error

### ISSUE THREAD

**Issue by Skybugdog** [Gandi-IDE/gandi-plugins#58]
![file_1718375890443_399](https://github.com/Gandi-IDE/gandi-plugins/assets/121487216/7e8670fa-4c9c-4238-8b7a-8dab1fed51de)
For the actual code, the plugin name (aaa-bbb) should be set between the first and second parameters of the sample code.
README is outdated. Can mislead new developers.

**Comment by MoreBugOfDog** [comment]
@zxq142857

**Comment by zxq142857** [comment]
https://github.com/Gandi-IDE/gandi-plugins/pull/62
