### ISSUE TITLE
Expose cooperation data to plugins

### ISSUE THREAD

**Issue by sparrowhe** [Gandi-IDE/gandi-plugins#67]
## Background

The backend team is planning to implement a "Voice Cooperation" function in the Gandi IDE as a plugin. This function will allow users to chat with their team within the Gandi IDE.

## Requirements

An API Interface to access cooperation informations, including:

- [ ] Cooperation users info list
- [ ] Cooperation Event
- - [ ] User Join
- - [ ] User Left
- [ ] Display a custom cursor message popup

For more details, contact me or make a comment below.

Best Regards.

**Comment by fath11** [comment]
oh shit we've unlocked Gandi IDE's Backend team characters pack 😱😱😱

**Comment by zxq142857** [comment]
I'm planning to add a teamworkManager object to PluginContext. [Here's](https://github.com/Gandi-IDE/gandi-plugins/blob/feat-support/src/types/teamwork.d.ts) its type definition. Let me know if there's anything else you need

**Comment by zxq142857** [comment]
You can get the latest onlineUsers like this:
```
  function onOnlineUsersUpdate (onlineUsers) {
      console.log('onlineUsers', onlineUsers);
  }
  // Subscribe
  teamworkManager.on('online_users_update',  onOnlineUsersUpdate);
  // Unsubscribe
  teamworkManager.off('online_users_update',  onOnlineUsersUpdate);
```

**Comment by sparrowhe** [comment]
> I'm planning to add a teamworkManager object to PluginContext. [Here's](https://github.com/Gandi-IDE/gandi-plugins/blob/feat-support/src/types/teamwork.d.ts) its type definition. Let me know if there's anything else you need

Can I get if a project is a teamwork project or not? I would like to add some logic to let users know they can only use voice cooperation function when they under a teamwork and login as a user.

**Comment by zxq142857** [comment]
> > > I'm planning to add a teamworkManager object to PluginContext. [Here's](https://github.com/Gandi-IDE/gandi-plugins/blob/feat-support/src/types/teamwork.d.ts) its type definition. Let me know if there's anything else you need
> >
> > Can I get if a project is a teamwork project or not? I would like to add some logic to let users know they can only use voice cooperation function when they under a teamwork and login as a user.
>
> `teamworkManager` is only available in collaboration mode; otherwise, it will be null. Users must be logged in to enter collaboration mode
